[font]
size = 15

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[general]
import = ["/home/daniel/.config/alacritty/palette.toml"]

[window]
opacity = 0.95
[window.padding]
x = 12
y = 12
