vim.cmd.highlight("clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd.syntax("reset")
end

vim.g.colors_name = "palette"

local c = {
  pink = "#FB6060",
  purple = "#B287FF",
  blue = "#66D9EF",
  green = "#A3E076",
  orange = "#FD971F",
  yellow = "#FFD569",
  brown = "#E6B362",
  sea_green = "#529B2F",
  dark_orange = "#C86F02",
  dark_brown = "#49483E",
  dark_blue = "#18B498",
  ghost = "#F8F8F0",
  light_ghost = "#F5F5F5",
  light_gray = "#CCCCCC",
  dark_gray = "#888888",
  level_9 = "#AAB2C3",
  level_8 = "#5B6478",
  level_7 = "#464F5E",
  level_6 = "#404855",
  level_5 = "#383F4B",
  level_4 = "#30353F",
  level_3 = "#2D333C",
  level_2 = "#292E36",
  level_1 = "#22272D",
}

local set = vim.api.nvim_set_hl
local groups = {
  Normal = { fg = c.ghost, bg = c.level_1 },
  NormalNC = { fg = c.light_gray, bg = c.level_1 },
  NormalFloat = { fg = c.ghost, bg = c.level_2 },
  FloatBorder = { fg = c.level_7, bg = c.level_2 },
  FloatTitle = { fg = c.purple, bg = c.level_2, bold = true },
  ColorColumn = { bg = c.level_2 },
  Cursor = { fg = c.level_1, bg = c.ghost },
  lCursor = { fg = c.level_1, bg = c.ghost },
  CursorIM = { fg = c.level_1, bg = c.purple },
  CursorColumn = { bg = c.level_2 },
  CursorLine = { bg = c.level_2 },
  CursorLineNr = { fg = c.yellow, bg = c.level_2, bold = true },
  LineNr = { fg = c.level_8, bg = c.level_1 },
  SignColumn = { fg = c.level_7, bg = c.level_1 },
  FoldColumn = { fg = c.level_8, bg = c.level_1 },
  Folded = { fg = c.level_9, bg = c.level_3 },
  EndOfBuffer = { fg = c.level_1 },
  NonText = { fg = c.level_6 },
  Whitespace = { fg = c.level_5 },
  SpecialKey = { fg = c.level_7 },
  Visual = { bg = c.level_5 },
  VisualNOS = { bg = c.level_5 },
  Search = { fg = c.level_1, bg = c.yellow },
  IncSearch = { fg = c.level_1, bg = c.green, bold = true },
  CurSearch = { fg = c.level_1, bg = c.orange, bold = true },
  Substitute = { fg = c.level_1, bg = c.pink },
  MatchParen = { fg = c.yellow, bg = c.level_4, bold = true },
  Pmenu = { fg = c.light_ghost, bg = c.level_3 },
  PmenuSel = { fg = c.level_1, bg = c.blue, bold = true },
  PmenuSbar = { bg = c.level_4 },
  PmenuThumb = { bg = c.level_8 },
  StatusLine = { fg = c.ghost, bg = c.level_5 },
  StatusLineNC = { fg = c.dark_gray, bg = c.level_3 },
  WinSeparator = { fg = c.level_5, bg = c.level_1 },
  VertSplit = { fg = c.level_5, bg = c.level_1 },
  TabLine = { fg = c.level_9, bg = c.level_3 },
  TabLineFill = { bg = c.level_2 },
  TabLineSel = { fg = c.level_1, bg = c.purple, bold = true },
  WinBar = { fg = c.level_9, bg = c.level_1 },
  WinBarNC = { fg = c.level_8, bg = c.level_1 },
  Title = { fg = c.purple, bold = true },
  Directory = { fg = c.blue },
  Question = { fg = c.green },
  MoreMsg = { fg = c.green },
  ModeMsg = { fg = c.yellow, bold = true },
  WarningMsg = { fg = c.orange },
  ErrorMsg = { fg = c.pink, bold = true },
  WildMenu = { fg = c.level_1, bg = c.blue },

  Comment = { fg = c.dark_gray, italic = true },
  Constant = { fg = c.orange },
  String = { fg = c.green },
  Character = { fg = c.green },
  Number = { fg = c.orange },
  Boolean = { fg = c.pink, bold = true },
  Float = { fg = c.orange },
  Identifier = { fg = c.light_ghost },
  Function = { fg = c.blue },
  Statement = { fg = c.purple },
  Conditional = { fg = c.purple },
  Repeat = { fg = c.purple },
  Label = { fg = c.yellow },
  Operator = { fg = c.pink },
  Keyword = { fg = c.purple },
  Exception = { fg = c.pink },
  PreProc = { fg = c.brown },
  Include = { fg = c.purple },
  Define = { fg = c.purple },
  Macro = { fg = c.brown },
  PreCondit = { fg = c.brown },
  Type = { fg = c.yellow },
  StorageClass = { fg = c.yellow },
  Structure = { fg = c.yellow },
  Typedef = { fg = c.yellow },
  Special = { fg = c.dark_blue },
  SpecialChar = { fg = c.dark_blue },
  Tag = { fg = c.blue },
  Delimiter = { fg = c.level_9 },
  SpecialComment = { fg = c.sea_green, italic = true },
  Debug = { fg = c.orange },
  Underlined = { fg = c.blue, underline = true },
  Ignore = { fg = c.level_7 },
  Error = { fg = c.pink, bold = true },
  Todo = { fg = c.level_1, bg = c.yellow, bold = true },

  Added = { fg = c.green },
  Changed = { fg = c.yellow },
  Removed = { fg = c.pink },
  DiffAdd = { fg = c.green, bg = c.level_3 },
  DiffChange = { fg = c.yellow, bg = c.level_3 },
  DiffDelete = { fg = c.pink, bg = c.level_3 },
  DiffText = { fg = c.level_1, bg = c.yellow, bold = true },

  DiagnosticError = { fg = c.pink },
  DiagnosticWarn = { fg = c.orange },
  DiagnosticInfo = { fg = c.blue },
  DiagnosticHint = { fg = c.dark_blue },
  DiagnosticOk = { fg = c.green },
  DiagnosticUnderlineError = { undercurl = true, sp = c.pink },
  DiagnosticUnderlineWarn = { undercurl = true, sp = c.orange },
  DiagnosticUnderlineInfo = { undercurl = true, sp = c.blue },
  DiagnosticUnderlineHint = { undercurl = true, sp = c.dark_blue },

  SpellBad = { undercurl = true, sp = c.pink },
  SpellCap = { undercurl = true, sp = c.blue },
  SpellLocal = { undercurl = true, sp = c.dark_blue },
  SpellRare = { undercurl = true, sp = c.purple },

  TelescopeNormal = { fg = c.light_ghost, bg = c.level_2 },
  TelescopeBorder = { fg = c.level_6, bg = c.level_2 },
  TelescopePromptNormal = { fg = c.ghost, bg = c.level_3 },
  TelescopePromptBorder = { fg = c.purple, bg = c.level_3 },
  TelescopePromptTitle = { fg = c.level_1, bg = c.purple, bold = true },
  TelescopePreviewTitle = { fg = c.level_1, bg = c.blue, bold = true },
  TelescopeResultsTitle = { fg = c.level_1, bg = c.green, bold = true },
  TelescopeSelection = { fg = c.ghost, bg = c.level_5, bold = true },
  TelescopeMatching = { fg = c.yellow, bold = true },

  NeoTreeNormal = { fg = c.light_gray, bg = c.level_2 },
  NeoTreeNormalNC = { fg = c.light_gray, bg = c.level_2 },
  NeoTreeDirectoryName = { fg = c.blue },
  NeoTreeDirectoryIcon = { fg = c.blue },
  NeoTreeRootName = { fg = c.purple, bold = true },
  NeoTreeFileNameOpened = { fg = c.yellow, bold = true },
  NeoTreeGitAdded = { fg = c.green },
  NeoTreeGitModified = { fg = c.yellow },
  NeoTreeGitDeleted = { fg = c.pink },
  NeoTreeIndentMarker = { fg = c.level_6 },
  NeoTreeWinSeparator = { fg = c.level_4, bg = c.level_1 },

  BlinkCmpMenu = { fg = c.light_ghost, bg = c.level_3 },
  BlinkCmpMenuBorder = { fg = c.level_6, bg = c.level_3 },
  BlinkCmpMenuSelection = { fg = c.level_1, bg = c.blue, bold = true },
  BlinkCmpLabelMatch = { fg = c.yellow, bold = true },
  BlinkCmpKind = { fg = c.purple },
  BlinkCmpDoc = { fg = c.light_ghost, bg = c.level_2 },
  BlinkCmpDocBorder = { fg = c.level_6, bg = c.level_2 },
  BlinkCmpSignatureHelp = { fg = c.light_ghost, bg = c.level_2 },
  BlinkCmpSignatureHelpBorder = { fg = c.level_6, bg = c.level_2 },

  RenderMarkdownH1Bg = { fg = c.level_1, bg = c.purple, bold = true },
  RenderMarkdownH2Bg = { fg = c.level_1, bg = c.blue, bold = true },
  RenderMarkdownH3Bg = { fg = c.level_1, bg = c.green, bold = true },
  RenderMarkdownCode = { bg = c.level_2 },
  RenderMarkdownBullet = { fg = c.orange },
  RenderMarkdownLink = { fg = c.blue, underline = true },
}

for group, opts in pairs(groups) do
  set(0, group, opts)
end

local links = {
  ["@variable"] = "Identifier",
  ["@variable.builtin"] = "Special",
  ["@variable.parameter"] = "Identifier",
  ["@variable.member"] = "Identifier",
  ["@constant"] = "Constant",
  ["@constant.builtin"] = "Constant",
  ["@module"] = "Type",
  ["@string"] = "String",
  ["@string.escape"] = "SpecialChar",
  ["@character"] = "Character",
  ["@boolean"] = "Boolean",
  ["@number"] = "Number",
  ["@function"] = "Function",
  ["@function.builtin"] = "Function",
  ["@function.call"] = "Function",
  ["@function.method"] = "Function",
  ["@constructor"] = "Type",
  ["@keyword"] = "Keyword",
  ["@keyword.function"] = "Keyword",
  ["@keyword.return"] = "Keyword",
  ["@keyword.operator"] = "Operator",
  ["@operator"] = "Operator",
  ["@type"] = "Type",
  ["@type.builtin"] = "Type",
  ["@property"] = "Identifier",
  ["@attribute"] = "PreProc",
  ["@punctuation.bracket"] = "Delimiter",
  ["@punctuation.delimiter"] = "Delimiter",
  ["@tag"] = "Tag",
  ["@tag.attribute"] = "Identifier",
  ["@tag.delimiter"] = "Delimiter",
  ["@comment"] = "Comment",
  ["@markup.heading"] = "Title",
  ["@markup.link"] = "Underlined",
  ["@markup.raw"] = "String",
  ["@markup.list"] = "Special",
  LspReferenceText = "Visual",
  LspReferenceRead = "Visual",
  LspReferenceWrite = "Visual",
}

for group, target in pairs(links) do
  set(0, group, { link = target })
end

vim.g.terminal_color_0 = c.level_1
vim.g.terminal_color_1 = c.pink
vim.g.terminal_color_2 = c.green
vim.g.terminal_color_3 = c.yellow
vim.g.terminal_color_4 = c.blue
vim.g.terminal_color_5 = c.purple
vim.g.terminal_color_6 = c.dark_blue
vim.g.terminal_color_7 = c.light_gray
vim.g.terminal_color_8 = c.dark_gray
vim.g.terminal_color_9 = c.orange
vim.g.terminal_color_10 = c.green
vim.g.terminal_color_11 = c.brown
vim.g.terminal_color_12 = c.blue
vim.g.terminal_color_13 = c.purple
vim.g.terminal_color_14 = c.dark_blue
vim.g.terminal_color_15 = c.ghost

-- Trasparenza: rimuovi gli sfondi base per far vedere Alacritty
local transparent_groups = {
  "Normal",
  "NormalNC",
  "NormalFloat",
  "FloatBorder",
  "FloatTitle",
  "LineNr",
  "SignColumn",
  "FoldColumn",
  "CursorLine",
  "CursorLineNr",
  "EndOfBuffer",
  "StatusLine",
  "StatusLineNC",
  "WinSeparator",
  "VertSplit",
  "TabLine",
  "TabLineFill",
  "WinBar",
  "WinBarNC",
  "TelescopeNormal",
  "TelescopeBorder",
  "TelescopePromptNormal",
  "TelescopePromptBorder",
  "TelescopePromptTitle",
  "TelescopePreviewTitle",
  "TelescopeResultsTitle",
  "NeoTreeNormal",
  "NeoTreeNormalNC",
  "NeoTreeWinSeparator",
  "BlinkCmpMenu",
  "BlinkCmpMenuBorder",
  "BlinkCmpDoc",
  "BlinkCmpDocBorder",
  "BlinkCmpSignatureHelp",
  "BlinkCmpSignatureHelpBorder",
  "RenderMarkdownCode",
}

for _, group in ipairs(transparent_groups) do
  vim.api.nvim_set_hl(0, group, { bg = "NONE" })
end
